spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/raffedb #?allowPublicKeyRetrieval=false&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
        lob:
        non_contextual_creation: true
    show-sql: true

# Configuración adicional (opcional)
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
