spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/realstatedb #?allowPublicKeyRetrieval=false&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
        lob:
        non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG
    org.thymeleaf.spring5: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG