#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/login_system
#        username: root
#        password: 1243
#    jpa:
#        hibernate:
#            ddl-auto: update
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQLDialect
#
