logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: INFO
server:
  port: 8080
spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/jcodeappbase
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc: 'null'
        lob: 'null'
        non_contextual_creation: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.sql
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false
    mode: HTML
    reactive:
      max-chunk-size: 8192
    suffix: .html
