-- liquibase formatted sql

-- changeset unifay:1720726503263-1
CREATE SEQUENCE  IF NOT EXISTS contact_form_entity_seq INCREMENT BY 50;

-- changeset unifay:1720726503263-2
CREATE SEQUENCE  IF NOT EXISTS image_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-3
CREATE SEQUENCE  IF NOT EXISTS image_seq INCREMENT BY 50;

-- changeset unifay:1720726503263-4
CREATE SEQUENCE  IF NOT EXISTS logs_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-5
CREATE SEQUENCE  IF NOT EXISTS property_contact_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-6
CREATE SEQUENCE  IF NOT EXISTS property_contact_seq INCREMENT BY 50;

-- changeset unifay:1720726503263-7
CREATE SEQUENCE  IF NOT EXISTS property_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-8
CREATE SEQUENCE  IF NOT EXISTS roles_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-9
CREATE SEQUENCE  IF NOT EXISTS tutorials_seq INCREMENT BY 50;

-- changeset unifay:1720726503263-10
CREATE SEQUENCE  IF NOT EXISTS users_id_seq INCREMENT BY 1;

-- changeset unifay:1720726503263-11
CREATE TABLE contact_form (id BIGINT NOT NULL, email VARCHAR(255), message VARCHAR(255), name VARCHAR(255), subject VARCHAR(255), property_entity_id BIGINT, CONSTRAINT contact_form_entity_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-12
CREATE TABLE image (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), property_entity_id BIGINT, image_url VARCHAR(255), CONSTRAINT image_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-13
CREATE TABLE logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, method VARCHAR(255), remote_addr VARCHAR(255), timestamp TIMESTAMP WITHOUT TIME ZONE, uri VARCHAR(255), username VARCHAR(255), CONSTRAINT logs_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-14
CREATE TABLE property (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN, address VARCHAR(255), address_locality VARCHAR(255), address_postal_code VARCHAR(255), address_way_name VARCHAR(255), address_way_number VARCHAR(255), air_conditioning BOOLEAN, balcony BOOLEAN, cellphone BOOLEAN, chat BOOLEAN, community_expenses DOUBLE PRECISION, constructed_area DOUBLE PRECISION, contact_name VARCHAR(255), contact_phone VARCHAR(255), contact_postal_code VARCHAR(255), description VARCHAR(255), email BOOLEAN, energy_qualification VARCHAR(255), green_area BOOLEAN, house_condition VARCHAR(255), house_type VARCHAR(255), principal_image_url VARCHAR(255), num_bathrooms INTEGER, num_bedrooms INTEGER, operation_type VARCHAR(255), orientation_east BOOLEAN, orientation_north BOOLEAN, orientation_south BOOLEAN, orientation_west BOOLEAN, parking_place BOOLEAN, plot_area DOUBLE PRECISION, pool BOOLEAN, price DOUBLE PRECISION, property_status VARCHAR(255), property_type VARCHAR(255), status VARCHAR(255), storage_room BOOLEAN, title VARCHAR(255), type VARCHAR(255), usable_area DOUBLE PRECISION, wardrobes BOOLEAN, whatsapp BOOLEAN, property_contact_entity_id BIGINT, map_url VARCHAR(500), CONSTRAINT property_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-15
CREATE TABLE property_contact (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cellphone VARCHAR(255), chat VARCHAR(255), email VARCHAR(255), last_name VARCHAR(255), name VARCHAR(255), whatsapp VARCHAR(255), CONSTRAINT property_contact_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-16
CREATE TABLE property_type (id INTEGER NOT NULL, count INTEGER NOT NULL, delay DOUBLE PRECISION NOT NULL, icon VARCHAR(255), name VARCHAR(255), type VARCHAR(255), CONSTRAINT property_type_entity_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-17
CREATE TABLE roles (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT roles_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-18
CREATE TABLE tutorials (id INTEGER NOT NULL, description VARCHAR(256), level INTEGER NOT NULL, published BOOLEAN, title VARCHAR(128) NOT NULL, CONSTRAINT tutorials_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-19
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN, email VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, user_name VARCHAR(255) NOT NULL, CONSTRAINT users_pkey PRIMARY KEY (id));

-- changeset unifay:1720726503263-20
CREATE TABLE users_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL);

-- changeset unifay:1720726503263-21
ALTER TABLE users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- changeset unifay:1720726503263-22
ALTER TABLE roles ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);

-- changeset unifay:1720726503263-23
ALTER TABLE users_roles ADD CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

-- changeset unifay:1720726503263-24
ALTER TABLE property ADD CONSTRAINT fk6xtgml47mueo3r32g4f37g3oa FOREIGN KEY (property_contact_entity_id) REFERENCES property_contact (id) ON DELETE NO ACTION;

-- changeset unifay:1720726503263-25
ALTER TABLE contact_form ADD CONSTRAINT fkhtrv7lte0dtbwvkur3yptfsaq FOREIGN KEY (property_entity_id) REFERENCES property (id) ON DELETE NO ACTION;

-- changeset unifay:1720726503263-26
ALTER TABLE users_roles ADD CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE NO ACTION;

-- changeset unifay:1720726503263-27
ALTER TABLE image ADD CONSTRAINT fkod9suv8qr5l9lcwhgd0i9rli4 FOREIGN KEY (property_entity_id) REFERENCES property (id) ON DELETE NO ACTION;

